[project]
name = "bone-project-material"
version = "0.1.0"
requires-python = ">=3.7"
dependencies = [
    "alphashape>=1.3.1",
    "descartes>=1.1.0",
    "numpy>=1.21.6",
    "open3d>=0.17.0",
    "pandas>=1.1.5",
    "pywavefront>=1.3.3",
    "scikit-learn>=1.0.2",
    "shapely>=2.0.7",
]
